### ISSUE TITLE
[TASK] Implement Search Functionality

### ISSUE THREAD

**Issue by dro42** [bennilic/Billova#11]
**Task Description**  
Enable users to search for expenses by date or category.

**Steps to Complete**  
1. [ ] Add search UI for filtering expenses.  
2. [ ] Implement backend logic for searching data.  

**Expected Deliverables**  
- [ ] Working search functionality for expenses.

**Comment by SergiuCl** [comment]
Done in frontend using vanilla js datatables as part of the task https://github.com/bennilic/Billova/issues/6.
To check with SRS document if all the requirments are fulfilled.
