### ISSUE TITLE
[TASK] Budget Notification Feature

### ISSUE THREAD

**Issue by dro42** [bennilic/Billova#14]
**Task Description**  
Notify users when their set monthly budget is about to be reached.

**Steps to Complete**  
1. [ ] Add budget limit input in settings.  
2. [ ] Implement backend logic to calculate spending.  
3. [ ] Trigger notifications when nearing the budget.
