### ISSUE TITLE
[TASK] Store Past Receipts for Future Reference

### ISSUE THREAD

**Issue by dro42** [bennilic/Billova#27]
**Task Description**  
Enable users to access stored receipts for future reference.

**Steps to Complete**  
1. [ ] Create a UI section for viewing past receipts.  
2. [ ] Retrieve and display receipt images and details from the database.  

**Expected Deliverables**  
- [ ] Feature to browse and view past receipts.
