### ISSUE TITLE
[TASK] Backend Project Setup

### ISSUE THREAD

**Issue by dro42** [bennilic/Billova#32]
### **Task Description**  
Set up the backend skeleton for the project using Django. This includes configuring the API structure, initializing the database, and creating foundational components for smooth integration with the frontend. The backend will serve as the core processing unit, handling data persistence, API endpoints, and business logic.

---

### **Steps to Complete**

1. [x] **Set Up Django Project**  
   - Install Django in the virtual environment.  
   - Create a new Django project and an app for backend functionality:  
     ```bash
     django-admin startproject billova_backend  
     cd billova_backend  
     python manage.py startapp core  
     ```  

2. [ ] **Configure Core Settings**  
   - Set up project settings, including:  
     - **Database configuration** (SQLite initially, scalable to PostgreSQL if needed).  
     - **Installed apps**: Add `rest_framework` for API development and `corsheaders` for frontend-backend integration.  
     - **Static and Media Files** configurations.  
     - **Allowed hosts and middleware setup**.  

3. [x] **Initialize Database Models**  
   - Create models for core entities (with placeholders):  
     - **User**: For user authentication and management.  
     - **Expense**: For storing receipt data.  
     - **Category**: For expense categorization.  
   - Example:  
     ```python
     from django.db import models  

     class Expense(models.Model):  
         user = models.ForeignKey('auth.User', on_delete=models.CASCADE)  
         amount = models.DecimalField(max_digits=10, decimal_places=2)  
         category = models.CharField(max_length=100)  
         date = models.DateField()  
         description = models.TextField(blank=True)  
     ```  

4. [ ] **Create API Endpoints**  
   - Set up Django Rest Framework (DRF) for API development:  
     - Install DRF: `pip install djangorestframework`.  
     - Configure DRF in `settings.py`.  
     - Create **initial endpoints**:  
       - [x] List expenses (GET)  
       - [x] Add an expense (POST)  
       - [ ] User login and registration endpoints.  
   - Example:  
     ```python
     from rest_framework import viewsets  
     from .models import Expense  
     from .serializers import ExpenseSerializer  

     class ExpenseViewSet(viewsets.ModelViewSet):  
         queryset = Expense.objects.all()  
         serializer_class = ExpenseSerializer  
     ```

5. [x] **Set Up URL Routing**  
   - Configure API routes using DRF routers.  
   - Example:  
     ```python
     from django.urls import path, include  
     from rest_framework.routers import DefaultRouter  
     from .views import ExpenseViewSet  

     router = DefaultRouter()  
     router.register(r'expenses', ExpenseViewSet)  

     urlpatterns = [  
         path('api/', include(router.urls)),  
     ]  
     ```

6. [x] **Test API Functionality**  
   - Verify the API endpoints using tools like **Postman** or **cURL**.  
   - Ensure endpoints return appropriate responses and error handling is in place.

7. [x] **Setup Initial Admin Dashboard**  
   - Register models in Django Admin for easy management.  
   - Test admin access to ensure models like User and Expense are manageable.

8. [ ] **Directory Structure Setup**  
   - Establish a clean directory structure:  
     ```
     /billova_backend  
       ├── core/  
       │   ├── models.py  
       │   ├── views.py  
       │   ├── serializers.py  
       │   └── urls.py  
       ├── billova_backend/  
       │   ├── settings.py  
       │   ├── urls.py  
       │   ├── wsgi.py  
       │   └── asgi.py  
       └── db.sqlite3  
     ```

---

### **Expected Deliverables**  
- [ ] A Django project initialized with **Django Rest Framework (DRF)**.  
- [ ] Initial API endpoints for basic operations (e.g., list and add expenses).  
- [ ] Database models for **User**, **Expense**, and **Category** entities.  
- [ ] URL routing configured for the API.  
- [ ] Admin panel access configured and tested.  
- [ ] Clear and well-structured backend project directory.  

---

### **Additional Information**  
- **Django Documentation**: [https://docs.djangoproject.com](https://docs.djangoproject.com)  
- **Django Rest Framework Docs**: [https://www.django-rest-framework.org](https://www.django-rest-framework.org)  
- Use SQLite for initial testing; plan for PostgreSQL if scaling is required.  
- The backend API will serve as the data source for the frontend integration.
