### ISSUE TITLE
[TASK] CI/CD Pipeline Setup

### ISSUE THREAD

**Issue by dro42** [bennilic/Billova#33]
### **Task Description**  
Set up a Continuous Integration/Continuous Deployment (CI/CD) pipeline using **GitHub Actions** (or other tools) to automate code testing, linting, and deployment for both backend and frontend. This will ensure consistency, code quality, and automated deployment processes.

---

### **Steps to Complete**

1. [ ] **Set Up GitHub Actions Workflow**  
   - Create a `.github/workflows/` directory in the root of the project.  
   - Add separate workflows for **Backend** and **Frontend**.  

2. [ ] **Backend CI/CD Pipeline**  
   - **Continuous Integration**:  
     - Install project dependencies (`pip install -r requirements.txt`).  
     - Run backend tests using `pytest` or Django's test framework.  
     - Ensure database migrations work (using `makemigrations` and `migrate`).  
     - Add linting checks (e.g., **flake8** or **black** for Python code style).  
   - **Continuous Deployment**:  
     - Set up deployment to a cloud environment (e.g., Heroku, AWS, or DigitalOcean).  
     - Ensure database migrations and static file collection are part of the deployment process.

   **Example GitHub Actions YAML**:  
   ```yaml
   name: Backend CI/CD

   on: [push]

   jobs:
     test:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Set up Python
           uses: actions/setup-python@v3
           with:
             python-version: 3.10

         - name: Install Dependencies
           run: |
             pip install -r requirements.txt

         - name: Run Tests
           run: |
             python manage.py test
             
         - name: Lint Code
           run: |
             pip install flake8
             flake8 .

         - name: Deploy to Heroku (if tests pass)
           if: success()
           uses: akhileshns/heroku-deploy@v3.12.12
           with:
             heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
             heroku_app_name: "your-heroku-app-name"
             heroku_email: "your-email@example.com"
   ```

3. [ ] **Frontend CI/CD Pipeline**  
   - **Continuous Integration**:  
     - Install frontend dependencies (e.g., `npm install`).  
     - Run linting checks using tools like **ESLint**.  
     - Run frontend unit tests with **Jest** or another framework.  
   - **Continuous Deployment**:  
     - Deploy frontend to a hosting provider like **Vercel**, **Netlify**, or **AWS S3**.  

   **Example GitHub Actions YAML**:  
   ```yaml
   name: Frontend CI/CD

   on: [push]

   jobs:
     build:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout Code
           uses: actions/checkout@v3

         - name: Install Node.js
           uses: actions/setup-node@v3
           with:
             node-version: 16

         - name: Install Dependencies
           run: |
             npm install

         - name: Run Linter
           run: |
             npm run lint

         - name: Run Tests
           run: |
             npm test

         - name: Deploy to Netlify
           if: success()
           uses: nwtgck/actions-netlify@v1.2.3
           with:
             publish-dir: './dist'
             production-deploy: true
             github-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
   ```

4. [ ] **Environment Variables and Secrets**  
   - Add environment variables and secrets securely in **GitHub Actions Secrets**. Examples:  
     - `HEROKU_API_KEY`, `NETLIFY_AUTH_TOKEN`.  
     - Database credentials and API keys.

5. [ ] **Test the Pipelines**  
   - Push code to trigger workflows and ensure:  
     - Tests pass successfully.  
     - Linting results are clean.  
     - Deployment to backend and frontend hosting environments works as expected.  

6. [ ] **Documentation**  
   - Document the CI/CD setup process in a `README.md` or project documentation.  
   - Include instructions for setting up new environment variables and troubleshooting pipeline errors.

---

### **Expected Deliverables**  
- [ ] Two separate CI/CD pipelines configured for **Backend** and **Frontend** using GitHub Actions.  
- [ ] Automated testing (unit tests) and linting for both codebases.  
- [ ] Deployment to hosting providers (e.g., Heroku for backend, Netlify/Vercel for frontend).  
- [ ] Documentation outlining the CI/CD setup and environment configurations.

---

### **Additional Information**  
- **GitHub Actions Docs**: [https://docs.github.com/en/actions](https://docs.github.com/en/actions)  
- Tools to use:  
  - **Backend**: Django, pytest, flake8, Heroku/AWS for deployment.  
  - **Frontend**: npm, ESLint, Jest, Netlify/Vercel for deployment.  

---
