### ISSUE TITLE
[TASK] Add Logging to the Application and Django

### ISSUE THREAD

**Issue by dro42** [bennilic/Billova#34]
### **Task Description**  
Implement logging throughout the application to track errors, warnings, and key events. This includes configuring Django's built-in logging framework and adding custom log messages in critical areas of the app.

---

### **Steps to Complete**

1. **Configure Django Logging**  
   - Update the `LOGGING` dictionary in `settings.py` to include handlers, formatters, and loggers.  
   - Add log levels for debugging, warnings, errors, and critical events.  
   - Example configuration:  
     ```python
     LOGGING = {
         'version': 1,
         'disable_existing_loggers': False,
         'formatters': {
             'verbose': {
                 'format': '{levelname} {asctime} {module} {message}',
                 'style': '{',
             },
             'simple': {
                 'format': '{levelname} {message}',
                 'style': '{',
             },
         },
         'handlers': {
             'file': {
                 'level': 'DEBUG',
                 'class': 'logging.FileHandler',
                 'filename': 'debug.log',
                 'formatter': 'verbose',
             },
         },
         'loggers': {
             'django': {
                 'handlers': ['file'],
                 'level': 'DEBUG',
                 'propagate': True,
             },
             'app': {
                 'handlers': ['file'],
                 'level': 'DEBUG',
                 'propagate': True,
             },
         },
     }
     ```

2. **Add Logging in Critical Backend Functions**  
   - Add logging messages to key areas, such as:  
     - API endpoints.  
     - Database interactions.  
     - OCR processing logic.  
     - User authentication (e.g., login attempts).  
   - Example:  
     ```python
     import logging
     logger = logging.getLogger('app')

     def some_function():
         try:
             # Function logic
             logger.info('Function executed successfully.')
         except Exception as e:
             logger.error(f'Error occurred: {e}')
             raise
     ```

3. **Integrate Logging for Frontend Errors (Optional)**  
   - Set up API endpoints to log frontend errors sent via JavaScript.  
   - Use a logging library (e.g., **Sentry**) for capturing frontend issues.  

4. **Test Logging Output**  
   - Verify that log files are created and updated correctly.  
   - Test different log levels (DEBUG, INFO, WARNING, ERROR).  
   - Ensure sensitive information (e.g., passwords, user data) is not logged.

5. **Document Logging Practices**  
   - Add instructions for developers to use the logging framework in the codebase.  
   - Define guidelines for when and how to log messages.

---

### **Expected Deliverables**

- [ ] A functional logging configuration in `settings.py`.  
- [ ] Log files for capturing debug, info, warning, and error messages.  
- [ ] Custom log messages in critical backend functions.  
- [ ] Documentation on logging practices and usage.

---

### **Additional Information**

- **Django Logging Docs**: [https://docs.djangoproject.com/en/stable/topics/logging/](https://docs.djangoproject.com/en/stable/topics/logging/)  
- Consider using tools like **Sentry** or **Logstash** for advanced monitoring.

---
